INSERT INTO color(id, color) VALUES (1, '#00B0FF');
INSERT INTO color(id, color) VALUES (2, '#00BFA6');
INSERT INTO color(id, color) VALUES (3, '#F50057');
INSERT INTO color(id, color) VALUES (4, '#536DFE');
INSERT INTO color(id, color) VALUES (5, '#F9A826');
INSERT INTO color(id, color) VALUES (6, '#6C63FF');
INSERT INTO color(id, color) VALUES (7, '#F50004');
INSERT INTO color(id, color) VALUES (8, '#FFFFFF');
INSERT INTO color(id, color) VALUES (9, '#D9F900');
